-- Table user
CREATE TABLE user (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL,
	sex CHAR(1),
	password VARCHAR(100) NOT NULL,
	birthday DATE,
	signday DATETIME NOT NULL,
	status TINYINT UNSIGNED NOT NULL
) ENGINE=INNODB;

-- Table stars

CREATE TABLE stars (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	name VARCHAR(255) NOT NULL,
	text LONGTEXT NOT NULL,
	image LONGBLOB  NOT NULL,
	created_date DATETIME NOT NULL,
	tag INT UNSIGNED,
	posted TINYINT,
	CONSTRAINT fk_user_id
		FOREIGN KEY (user_id)
		REFERENCES user(id),
	CONSTRAINT fk_tag_id
		FOREIGN KEY (tag)
		REFERENCES tags(id)
) ENGINE=INNODB;

-- Table tags

CREATE TABLE tags (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	tag VARCHAR(50) NOT NULL
) ENGINE=INNODB;

