-- Table user
CREATE TABLE user (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL,
	sex CHAR(1),
	password VARCHAR(100) NOT NULL,
	birthday DATE,
	signday DATETIME NOT NULL,
	status TINYINT UNSIGNED NOT NULL
) ENGINE=INNODB;